### ISSUE TITLE
Configuration file locate issue

### ISSUE THREAD

**Issue by dlee640** [Miro001/Ouster-cartographer#1]
Dear author,

First off, thank you so much for this open source sharing.

I have OS0-32 myself, and I wanted to get familiar with your example before proceeding to your example.

Here is my issue. Upon running the slam_launch.sh, I get the following error

```
slambox@slambox-NUC10i7FNH:~/ouster_slam_ws/src$ bash slam_launch.sh
... logging to /home/slambox/.ros/log/2f907054-b8e4-11eb-8788-f8ac65d8d6d2/roslaunch-slambox-NUC10i7FNH-24521.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/__init__.py", line 332, in main
    p.start()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/parent.py", line 289, in start
    self._start_infrastructure()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/parent.py", line 238, in _start_infrastructure
    self._load_config()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/parent.py", line 144, in _load_config
    roslaunch_strs=self.roslaunch_strs, verbose=self.verbose)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/config.py", line 461, in load_config_default
    loader.load(f, config, argv=args, verbose=verbose)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 761, in load
    self._load_launch(launch, ros_config, is_core=core, filename=filename, argv=argv, verbose=verbose)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 733, in _load_launch
    self._recurse_load(ros_config, launch.childNodes, self.root_context, None, is_core, verbose)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 679, in _recurse_load
    self._param_tag(tag, context, ros_config, verbose=verbose)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 96, in call
    return f(*args, **kwds)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 271, in _param_tag
    value = self.param_value(verbose, name, ptype, *vals)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/loader.py", line 476, in param_value
    with open(textfile, 'r') as f:
IOError: [Errno 2] No such file or directory: u'.../src/ouster_slam_ws/configuration_files/os1_16.lua/urdf/os_sensor.urdf'
```

As you can see from the last line, it seems to have trouble locating the .lua configuration file for the cartographer.

Here is my .sh file,

```
#!/bin/bash
source ../devel/setup.bash

BAGPATH='.../OS1-16_city1.bag' #own path
CONFIGPATH='.../sample_config_file_16.json' #own path

CARTOCONF='.../src/ouster_slam_ws/configuration_files/os1_16.lua' #own path

roslaunch ouster_slam os_slam.launch \
                             udp_hostname:=169.254.207.33 \
                             replay:=true \
                             bag_filename:=${BAGPATH}\
                             metadata:=${CONFIGPATH}\
                             carto_conf:=${CARTOCONF}
```
As you can see, I have correctly inputted by CARTOCONF location. But from the error message, it seems to be adding `/urdf/os_sensor.urdf` to whatever that is typed for CARTOCONF. Is this supposed to happen or is this a bug? What do you mean by CARTOCONF here? I thought you are referring to .lua file, not the urdf file. 

Thank you for your generous help.

Best.

**Comment by Miro001** [comment]
In the *.sh script you **have to set  CARTOCONF to the cartographer configuration directory** (https://github.com/Miro001/Ouster-cartographer/tree/master/ouster_slam), not to a single configuration file. 

This is because the cartographer requires several configuration files to launch.
`CARTOCONF='.../src/ouster_slam/' ` #own path

**Comment by dlee640** [comment]
Hello, thank you again for your response.

I have actually left the sh file as is, which the CARTOCONF was set to `CARTOCONF='.../src/ouster_slam_ws/'` but I still get the error message below. Please check the last line, as it seems like the start up script has difficulty locating the /urdf/os_sensor.urdf file. Thank you.

```
slambox@slambox-NUC10i7FNH:~/ouster_slam_ws$ bash slam_launch.sh 
slam_launch.sh: line 2: ../devel/setup.bash: No such file or directory
... logging to /home/slambox/.ros/log/64215418-b985-11eb-950c-f8ac65d8d6d2/roslaunch-slambox-NUC10i7FNH-4410.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/__init__.py", line 332, in main
    p.start()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/parent.py", line 289, in start
    self._start_infrastructure()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/parent.py", line 238, in _start_infrastructure
    self._load_config()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/parent.py", line 144, in _load_config
    roslaunch_strs=self.roslaunch_strs, verbose=self.verbose)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/config.py", line 461, in load_config_default
    loader.load(f, config, argv=args, verbose=verbose)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 761, in load
    self._load_launch(launch, ros_config, is_core=core, filename=filename, argv=argv, verbose=verbose)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 733, in _load_launch
    self._recurse_load(ros_config, launch.childNodes, self.root_context, None, is_core, verbose)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 679, in _recurse_load
    self._param_tag(tag, context, ros_config, verbose=verbose)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 96, in call
    return f(*args, **kwds)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 271, in _param_tag
    value = self.param_value(verbose, name, ptype, *vals)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/loader.py", line 476, in param_value
    with open(textfile, 'r') as f:
IOError: [Errno 2] No such file or directory: u'.../src/ouster_slam_ws/urdf/os_sensor.urdf'

```

**Comment by dlee640** [comment]
![Screenshot from 2021-05-20 12-12-54](https://user-images.githubusercontent.com/60672433/119013192-c3eeb000-b964-11eb-87e9-7b8bf4c1a7b6.png)
Here is the directory screenshot from `~/ouster_slam_ws/` where I start the bash script.

**Comment by dlee640** [comment]
changing the ~/ notation to /home/USER/ solved this issue. Thank you.
